import argparse
import os
import sys
from datetime import datetime
from dotenv import load_dotenv

from utils import parse_channel_input, format_number
from youtube_api import get_channel_id, get_channel_stats, get_recent_video_ids, get_video_stats
from analysis import calculate_averages, calculate_engagement_rate, get_engagement_rating, get_ai_insight

load_dotenv()


def build_markdown(channel_stats: dict, averages: dict, engagement_rate: float, rating: str, num_videos: int, ai_insight: str = "") -> str:
    title = channel_stats["title"]
    subscribers = format_number(channel_stats["subscriber_count"])
    total_videos = format_number(channel_stats["video_count"])
    avg_views = format_number(round(averages["avg_views"]))
    avg_likes = format_number(round(averages["avg_likes"]))
    avg_comments = format_number(round(averages["avg_comments"]))
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    rating_guide = (
        "| Engagement Rate | Rating |\n"
        "|-----------------|--------|\n"
        "| Below 2%        | Low    |\n"
        "| 2% – 5%         | Good   |\n"
        "| Above 5%        | Excellent |"
    )

    lines = [
        f"# YouTube Channel Analysis Report",
        f"",
        f"**Generated:** {generated_at}",
        f"",
        f"---",
        f"",
        f"## Channel Overview",
        f"",
        f"| Metric          | Value          |",
        f"|-----------------|----------------|",
        f"| **Channel**     | {title}        |",
        f"| **Subscribers** | {subscribers}  |",
        f"| **Total Videos**| {total_videos} |",
        f"",
        f"---",
        f"",
        f"## Recent Video Averages *(last {num_videos} videos)*",
        f"",
        f"| Metric             | Value         |",
        f"|--------------------|---------------|",
        f"| **Average Views**  | {avg_views}   |",
        f"| **Average Likes**  | {avg_likes}   |",
        f"| **Average Comments**| {avg_comments}|",
        f"",
        f"---",
        f"",
        f"## Engagement",
        f"",
        f"**Engagement Rate:** `{engagement_rate:.2f}%` — **{rating}**",
        f"",
        f"> Engagement Rate = (Average Likes + Average Comments) / Average Views × 100",
        f"",
        f"### Rating Guide",
        f"",
        rating_guide,
        f"",
        f"---",
        f"",
    ]

    if ai_insight:
        lines += [
            f"## AI Business Insight",
            f"",
            f"> {ai_insight}",
            f"",
            f"---",
            f"",
        ]

    lines.append(f"*Report generated by YouTube Channel Analyzer*")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Analyse a YouTube channel's engagement metrics and export a Markdown report."
    )
    parser.add_argument("channel", help="YouTube channel name, @handle, or URL")
    parser.add_argument(
        "--videos",
        type=int,
        default=10,
        metavar="N",
        help="Number of recent videos to analyse (default: 10)",
    )
    parser.add_argument(
        "--ai",
        action="store_true",
        help="Generate an AI-powered business insight via Claude",
    )
    parser.add_argument(
        "--output",
        metavar="FILE",
        default=None,
        help="Output file path for the Markdown report (default: report_<channel>.md)",
    )
    args = parser.parse_args()

    query = parse_channel_input(args.channel)

    try:
        print(f"\nLooking up channel: {query!r} ...")
        channel_info = get_channel_id(query)
        channel_id = channel_info["id"]

        print("Fetching channel statistics ...")
        channel_stats = get_channel_stats(channel_id)

        print(f"Fetching {args.videos} most recent videos ...")
        video_ids = get_recent_video_ids(channel_stats["uploads_playlist_id"], max_results=args.videos)
        if not video_ids:
            print("No videos found for this channel.")
            sys.exit(1)

        print(f"Fetching stats for {len(video_ids)} videos ...")
        video_stats = get_video_stats(video_ids)

        averages = calculate_averages(video_stats)
        engagement_rate = calculate_engagement_rate(
            averages["avg_likes"], averages["avg_comments"], averages["avg_views"]
        )
        rating = get_engagement_rating(engagement_rate)

        ai_insight = ""
        if args.ai:
            print("Generating AI insight ...")
            metrics = {
                **channel_stats,
                **averages,
                "engagement_rate": engagement_rate,
                "engagement_rating": rating,
            }
            ai_insight = get_ai_insight(metrics)

        report_md = build_markdown(channel_stats, averages, engagement_rate, rating, len(video_ids), ai_insight)

        # Determine output filename
        if args.output:
            output_path = args.output
        else:
            safe_name = channel_stats["title"].replace(" ", "_").replace("/", "-")
            output_path = f"report_{safe_name}.md"

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report_md)

        # Print full summary to terminal
        print(f"\n{'='*50}")
        print(f"Channel: {channel_stats['title']}")
        print(f"Subscribers: {format_number(channel_stats['subscriber_count'])}")
        print(f"Total Videos: {format_number(channel_stats['video_count'])}")
        print(f"\nRecent Video Averages (last {len(video_ids)} videos)")
        print(f"Average Views: {format_number(round(averages['avg_views']))}")
        print(f"Average Likes: {format_number(round(averages['avg_likes']))}")
        print(f"Average Comments: {format_number(round(averages['avg_comments']))}")
        print(f"\nEngagement Rate: {engagement_rate:.2f}% — {rating}")
        if ai_insight:
            print(f"\nAI Insight: {ai_insight}")
        print(f"{'='*50}")
        print(f"\nReport saved to: {os.path.abspath(output_path)}\n")

    except ValueError as e:
        print(f"\nError: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"\nUnexpected error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
